{
	"106": {
		"0410": {
			"name": "PythonCore::ValidationError",
			"message": "",
			"short_description": "Unknown cause.",
			"long_description": "Unknown cause.",
			"short_solution": "Unknown solution.",
			"long_solution": "Unknown solution.",
			"support_link": "https://preten.do/106-0410"
		}
	}
}