{
	"106": {
		"0402": {
			"name": "PythonCore::TypeError",
			"message": "",
			"short_description": "Unknown cause.",
			"long_description": "Unknown cause.",
			"short_solution": "Unknown solution.",
			"long_solution": "Unknown solution.",
			"support_link": "https://preten.do/106-0402"
		}
	}
}